csv: test.csv

models:
  pixtral: mistralai/Pixtral-12B-2409
  llama: meta-llama/Llama-3.2-11B-Vision-Instruct
  phi: microsoft/Phi-3.5-vision-instruct
  llava: llava-hf/llava-v1.6-mistral-7b-hf

experiments:
  1.1.1:
    system_prompt: "You are a math assistant responsible for evaluating handwritten math problems at the middle or high school level. Your task is to analyze the given Image, which contains the handwritten math Question-Answer pair, and determine whether the solution contains any errors. Follow the specific instructions provided carefully and output your response strictly in the requested format. Ensure that your evaluation is precise, accurate, and based solely on the information visible in the Image."
    user_prompt:
      "'The image provided contains a handwritten problem consisting of both a Question and an Answer at a middle or high school level. Your task is to analyze the Answer to determine whether there is any error. If the problem is multiple-choice (MCQ), judge the presence or absence of error based only on the explanation given in the Answer, not the option selected by the student.



      Provide a binary output indicating whether an error exists (1 for error, 0 for no error).



      Please follow the exact format below without adding any extra information:



      **Error:** <0 or 1>

      '"
  1.1.2:
    system_prompt: "You are a math assistant responsible for evaluating handwritten math problems at the middle or high school level. Your task is to analyze the given Image, which contains the handwritten math Question-Answer pair, and determine whether the solution contains any errors. Follow the specific instructions provided carefully and output your response strictly in the requested format. Ensure that your evaluation is precise, accurate, and based solely on the information visible in the Image."
    user_prompt:
      "'The image provided contains a handwritten problem consisting of both a Question and an Answer at a middle or high school level. Your task is to analyze the Answer to determine whether there is any error. Begin by providing a detailed, step-by-step reasoning for your analysis, explaining where and why you believe an error is present or absent in the Answer. If the problem is multiple-choice (MCQ), judge the presence or absence of error based only on the explanation given in the Answer, not the option selected by the student.

      After the reasoning, provide a binary output indicating whether an error exists (1 for error, 0 for no error).



      Please follow the exact format below without adding any extra information:



      **Reasoning:** <Step-by-Step Explanation of Error Presence or Absence>

      **Error:** <0 or 1>'"
  1.1.3:
    system_prompt: "You are a math assistant responsible for evaluating handwritten math problems at the middle or high school level. Your task is to analyze the given Image, which contains the handwritten math Question-Answer pair, and determine whether the solution contains any errors. Follow the specific instructions provided carefully and output your response strictly in the requested format. Ensure that your evaluation is precise, accurate, and based solely on the information visible in the Image."
    user_prompt: "'

      The image provided contains a handwritten problem with both a Question and an Answer at a middle or high school level. Your task is to internally perform OCR to extract the content of the handwritten text and analyze it to determine whether there is an error in the Answer. Do not output the OCR results directly. Use the OCR output solely to improve the accuracy of your reasoning regarding the presence or absence of an error in the Answer.



      Begin by providing a detailed, step-by-step reasoning for your analysis, explaining where and why you believe an error is present or absent in the Answer. If the problem is multiple-choice (MCQ), base your judgment solely on the explanation provided in the Answer, not the option selected by the student.



      After your reasoning, provide a binary output indicating whether an error exists (1 for error, 0 for no error).



      Please follow the exact format below without adding any extra information:



      **Reasoning:** <Step-by-Step Explanation of Error Presence or Absence>

      **Error:** <0 or 1>

      '"
